import Head from 'next/head'
import { MDXRemote } from 'next-mdx-remote' 
import { getFileBySlug, getFiles } from '../lib/mdx'

import MDXComponents from '../components/MDXComponents'



export default function Post({ source, frontmatter }) {
  return (
    <>

        <Head>
          <title>Blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

          <MDXRemote {...source} components={MDXComponents}/>
    </>
  )
}

export async function getStaticProps({ params }){
  const { source, frontmatter } = await getFileBySlug(params.slug)

  return{
    props: {source, frontmatter}
  }
}



export async function getStaticPaths(){
  const posts = await getFiles()
  const paths = posts.map((post) => ({
    params: {
      slug: post.replace(/\.mdx/, "")
    }
  }))

  return{
    paths,
    fallback: false
  }
}